### ISSUE TITLE
[ Feature Request ] Config parameters as command line arguments.

### ISSUE THREAD

**Issue by agithomas** [elastic/TSDB-migration-test-kit#1]
Please have the arguments captured as command-line arguments. Currently, on pulling the latest code from the main branch, some of the existing configurations (in main.py) will be overwritten. Also, having a command line argument helps this tool integrate with other tools.

Please have at least the below-mentioned config as command-line arguments

- ca path
- setting index
- mapping index
- overlapping files flag
- datastream name
- tsdb index name

You may have default values for some of the above. Overwrite the default values with the values received from command line.

**Comment by constanca-m** [comment]
@agithomas Done! Hope it all works!
