### ISSUE TITLE
[Bug] Readme contains deprecated or incorrect flag names 

### ISSUE THREAD

**Issue by agithomas** [elastic/TSDB-migration-test-kit#2]
If my understanding is correct, `settings_index` is deprecated, instead `settings_mappings_index` is used. 

Below mentioned documentation contains is showing name of deprecated flags. Please correct them. 

<img width="901" alt="image" src="https://github.com/elastic/TSDB-migration-test-kit/assets/101976829/df12d1bb-c87a-4878-a959-5db309743723">

**Comment by constanca-m** [comment]
Thanks @agithomas for bringing it up! I changed the variable name to be more clear but I forgot to update it in all places. Need to pay more attention :) it's fixed now!
